<?php
/**
 * ApiGen - API Generator.
 *
 * Copyright (c) 2010 David Grudl (http://davidgrudl.com)
 * Copyright (c) 2011 Ondřej Nešpor (http://andrewsville.cz)
 * Copyright (c) 2011 Jaroslav Hanslík (http://kukulich.cz)
 *
 * This source file is subject to the "Nette license", and/or
 * GPL license. For more information please see http://nette.org
 */

namespace Apigen\Plugin;
use Apigen;

/**
 * Page generator plugin interface.
 *
 * This interface allows creating whole custom pages in the documentation
 * and adding appropriate links to the sidebar menu.
 *
 * @author Ondřej Nešpor
 * @author Jaroslav Hanslík
 */
interface Page extends Apigen\Plugin
{
	/**#@+
	 * Top menu.
	 *
	 * @var integer
	 */
	const MENU_TOP = 1;

	/**
	 * Main (side) menu.
	 */
	const MENU_MAIN = 2;

	/**
	 * Footer.
	 *
	 * Not exactly a menu, but allows placing additional links.
	 */
	const MENU_FOOTER = 3;

	/**
	 * Place menu above.
	 */
	const PLACEMENT_ABOVE = 0x1;

	/**
	 * Place menu below.
	 */
	const PLACEMENT_BELOW = 0x4;

	/**
	 * Place menu next to the classes list.
	 */
	const PLACEMENT_CLASSES = 0x10;

	/**
	 * Place menu next to the interfaces list.
	 */
	const PLACEMENT_INTERFACES = 0x20;

	/**
	 * Place menu next to the exceptions list.
	 */
	const PLACEMENT_EXCEPTIONS = 0x30;

	/**
	 * Place menu next to the namespaces list.
	 */
	const PLACEMENT_NAMESPACES = 0x40;

	/**
	 * Place menu next to the packages list.
	 */
	const PLACEMENT_PACKAGES = 0x50;
	/**#@-*/

	/**
	 * Returns definition of separate menu items for a given menu.
	 *
	 * @param integer Menu position
	 * @return array
	 */
	public function getMenuItems($menu);

	/**
	 * Returns a whole menu definition for a given position.
	 *
	 * @return array
	 */
	public function getMenu($position);

	/**
	 * Renders pages.
	 *
	 * Please note, that pages have to be generated to the --destination directory.
	 * Therefore it is recommended to use the {@link \Apigen\Generator::getOutputPath()}
	 * method to get the absolute output filename from a relative one.
	 *
	 * Any variables inserted into the template will be available for use in all
	 * subsequent documentation pages. That is why it is desirable to unset() all
	 * variables that are not used anywhere else but in pages generated by this plugin.
	 *
	 * @see \Apigen\Generator::getOutputPath()
	 * @return boolean
	 */
	public function renderPages();
}
